apiVersion: secrets.hashicorp.com/v1alpha1
kind: VaultStaticSecret
metadata:
  name: profile-app
  namespace: app-dev
spec:
  type: kv-v2
  # mount path
  mount: kvv2
  # name of the secret
  name: backend/dev/profile
  # dest k8s secret
  destination:
    name: profile-creds
    create: true
  # static secret refresh interval
  refreshAfter: 30s